name: Main Workflow

# Trigger: s'executarà en fer push a la branca "nodejs_linter_job"
on:
  push:
    branches:
      - nodejs_linter_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del codi font
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Executar el linter
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true