name: Main Workflow

# S'executarà en fer push a la branca "nodejs_test_job"
on:
  push:
    branches:
      - nodejs_test_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del codi font
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Executar el linter
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    needs: linter-execution
    steps:
      -name: Checkout Code
       uses: actions/checkout@v4
      -name: Install Jest
       run: npm install jest --legacy-peer-deps
      -name: Run Jest Test
       run: npm run test